### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by mpariente** [fgnt/paderbox#2]
Thanks a lot for sharing this, that looks really nice !  :-)

- `transform_to_baseband` makes complete sense. Question : did you use it as input features to DNN, does it make any difference with or without the phase corrections? I intended to try but didn't do it yet.

- About the approach for the STFT / iSTFT, in particular about the biorthogonal synthesis window. 
  - I don't find the dissertation from which the equations are derived. Would it be possible to have a link to it? Or some other resources that explains the approach? It amounts to divide the time-domain synthesized signal by the sum of the overlap-added squared analysis windows right? 
  - If my understanding is correct, iSTFT(STFT(x)) == x for any window and any shift. However, if the STFT is modified (which is usually the case if we are about to take the iSTFT), the use of the biorthogonal synthesis window will bring time domain amplitude modulation. Did you make any experiments to quantify those artifacts and compare them against using the constant scaling factor? Especially for _bad_ window choices?

Cheers,

**Comment by LukasDrude** [comment]
`transform_to_baseband()` quite some time ago I used it as input features for a mask estimator. If you plot `arg(stft(x))` as a 2D image with and without the aforementioned transform, the target speaker is a bit better visible when using the transform. In principle, a network can learn this transformation itself.

**Comment by boeddeker** [comment]
Regarding the biorthogonal synthesis window, you can find the dissertation under
http://digital.ub.uni-paderborn.de/hsx/content/titleinfo/329824
but the dissertation is written in German.

In the dissertation for equation 5.85
`[FR94] S. Farkash und S. Raz: „Linear Systems in Gabor Time-Frequency Space“, IEEE Transactions on Signal Processing, Band 42(3), S. 611–617, März 1994.`
is cited for the criterion of the biorthogonal window.
Maybe there is also something written. But I haven't checked it.

Yes, the biorthogonal synthesis window is calculated such, that the overlap-add of the window function times the biorthogonal synthesis window is one. This is necessary for the `iSTFT(STFT(x)) == x` property.
This criterion is not unique.
We calculate the biorthogonal synthesis window such, that the biorthogonal synthesis window of a hann window with a 1/4 shift of the size is again a hann window, but scaled:
```python
    >>> analysis_window = signal.windows.hann(8+1)[:-1]
    >>> analysis_window
    array([0.        , 0.14644661, 0.5       , 0.85355339, 1.        ,
           0.85355339, 0.5       , 0.14644661])
    >>> _biorthogonal_window_brute_force(analysis_window, 2) * 3 / 2
    array([0.        , 0.14644661, 0.5       , 0.85355339, 1.        ,
           0.85355339, 0.5       , 0.14644661])
```

Yes, manipulating the STFT signal hurts the identity property. 
But we do not have such experiments.
As far as I know, it is common to use a window pair to do the STFT and the iSTFT with a fixed shift/size ratio. For example: both are hann windows and the ratio is `shift/size==1/4` (see librosa and tensorflow).

**Comment by mpariente** [comment]
Thanks both of you for your answers. 

> In principle, a network can learn this transformation itself.

In principle yes, but it's not an obvious transform and it might make things easier for the network, that's why I asked.
  
> Yes, the biorthogonal synthesis window is calculated such, that the overlap-add of the window function times the biorthogonal synthesis window is one. This is necessary for the `iSTFT(STFT(x)) == x` property.
> This criterion is not unique.
> We calculate the biorthogonal synthesis window such, that the biorthogonal synthesis window of a hann window with a 1/4 shift of the size is again a hann window, but scaled:
> 
> ```python
>     >>> analysis_window = signal.windows.hann(8+1)[:-1]
>     >>> analysis_window
>     array([0.        , 0.14644661, 0.5       , 0.85355339, 1.        ,
>            0.85355339, 0.5       , 0.14644661])
>     >>> _biorthogonal_window_brute_force(analysis_window, 2) * 3 / 2
>     array([0.        , 0.14644661, 0.5       , 0.85355339, 1.        ,
>            0.85355339, 0.5       , 0.14644661])
> ```
> 

Yes, `denominator` ([here](https://github.com/fgnt/paderbox/blob/master/paderbox/transform/module_stft.py#L480))is equal to one in this case right? So the synthesis window is equal to the analysis window. 

> Yes, manipulating the STFT signal hurts the identity property.
> But we do not have such experiments.
> As far as I know, it is common to use a window pair to do the STFT and the iSTFT with a fixed shift/size ratio. For example: both are hann windows and the ratio is `shift/size==1/4` (see librosa and tensorflow).

It is common to have a pair of windows for the STFT and iSTFT, I agree and that's fine for me. 
But dividing by the overlap-added square window seems wrong to me, even if it makes the unit test pass.
Thanks again, I'll try to take time to write an example for what I mean in the future.

**Comment by boeddeker** [comment]
We are not the only ones that use such a normalization.
For Torch I found https://github.com/pseeth/torch-stft/blob/master/torch_stft/stft.py
where they also use this normalization.

The normalization is necessary, otherwise the property `iSTFT(STFT(x)) == x` does not hold for every window, size and shift. I have no simple explanation why the denominator is the overlap-add of the square window. It takes a bit to explain. I only know the written explanation in the German dissertation from Krueger.

For some windows, you do not know the other window. In this case, the function calculates a solid reconstruction window.

Your assumption is right, that you shouldn't use arbitrary windows, sizes and shifts.
Here an example, where the shift is increased. A shift larger than 3/8 of the size seems to be a bad idea:

![image](https://user-images.githubusercontent.com/13744128/71828513-c23f8780-30a2-11ea-8eba-d887548ee051.png)

And a notebook to reproduce them:
[04 - Calculate biorthogonal window for STFT.ipynb.html.zip](https://github.com/fgnt/paderbox/files/4026736/04.-.Calculate.biorthogonal.window.for.STFT.ipynb.html.zip)

**Comment by mpariente** [comment]
> We are not the only ones that use such a normalization.
> For Torch I found https://github.com/pseeth/torch-stft/blob/master/torch_stft/stft.py
> where they also use this normalization.
> 

I know, and it is also the case in scipy at least, and maybe librosa. 
Still, I'm not convinced. I think it gives the wrong impression to the user that any choice of window and shift are fine, which is wrong.  
Maybe it's philosophical but I think the STFT shouldn't be unit-tested for perfect reconstruction, it will produce amplitude artifacts when the STFT is modified.

> The normalization is necessary, otherwise the property `iSTFT(STFT(x)) == x` does not hold for every window, size and shift. I have no simple explanation why the denominator is the overlap-add of the square window. It takes a bit to explain. I only know the written explanation in the German dissertation from Krueger.

The reason is clear for me, it gives the MMSE for the reconstruction for an unmodified STFT.  

> 
> For some windows, you do not know the other window. In this case, the function calculates a solid reconstruction window.
> 
> Your assumption is right, that you shouldn't use arbitrary windows, sizes and shifts.
> Here an example, where the shift is increased. A shift larger than 3/8 of the size seems to be a bad idea.

However, most DNN-based speech enhancement and source separation use an overlap of 50%. My guess is that this method will introduce more amplitude modulation artifacts in the resynthesis than the "classical" one. I'll try and quantify this at one point. 

Thanks for the examples.

**Comment by boeddeker** [comment]
> The reason is clear for me, it gives the MMSE for the reconstruction for an unmodified STFT.

Yes, but this is not the complete story. The boxcar window also fulfills this property for the hann window.

> I know, and it is also the case in scipy at least, and maybe librosa.
> Still, I'm not convinced. I think it gives the wrong impression to the user that any choice of window and shift are fine, which is wrong.
> Maybe it's philosophical but I think the STFT shouldn't be unit-tested for perfect reconstruction, it will produce amplitude artifacts when the STFT is modified.

But what would be the correct signature? Disable the window and shift argument? Only allow some window sizes? How do you find the reconstruction window? Also, the known pairs are obtained with a criterion.
Use the reconstruction window in the signature of the ISTFT is even worse, because then you can use unmatched windows in the STFT and ISTFT.

> However, most DNN-based speech enhancement and source separation use an overlap of 50%. My guess is that this method will introduce more amplitude modulation artifacts in the resynthesis than the "classical" one. I'll try and quantify this at one point.

Yes, this is likely. It would be interesting to read such an analysis.

**Comment by mpariente** [comment]
> > The reason is clear for me, it gives the MMSE for the reconstruction for an unmodified STFT.
> 
> Yes, but this is not the complete story. The boxcar window also fulfills this property for the hann window.

True.

> But what would be the correct signature? Disable the window and shift argument? Only allow some window sizes? How do you find the reconstruction window? Also, the known pairs are obtained with a criterion.

These are all legitimate questions, if I had the answers, I wouldn't be bothering you about this ;-)
The criterion for the classical approach is to have the least amount of oscillation in the OLAd windows.

> Use the reconstruction window in the signature of the ISTFT is even worse, because then you can use unmatched windows in the STFT and ISTFT.

I kind of agree on this one as well. 

I've been thinking about this for a while and didn't take the time to make thorough experiments yet. One thing I know is that I consistently got better results with "unormalized" STFT when using ConvTasnet with DFT filterbanks compared to using torch's stft.

Thanks for the discussion, I'll close this for now and open it if I have something interesting.

Very best, 
Manu
