### ISSUE TITLE
Citation with Zenodo

### ISSUE THREAD

**Issue by vsoch** [fgnt/paderbox#3]
heyo!

I saw in your README that you wrote:

> There is no clear way how to cite this repository for research. However, we would be grateful if directly import from this repository if you use, e.g., the STFT. We are also fine when you copy the code as long as it remains visible where you copied the code from.

And just wanted to suggest that you add the repository to [Zenodo](https://zenodo.org/), which would give a clear way to cite it. Happy Holidays!

**Comment by jensheit** [comment]
Hi vsoch,
thank you for alerting us to this possibility.
However, at the moment paderbox is just a collection of useful tools, the code which require proper citation are located in individual repositories. Those repositories already have a clear way to cite them.

**Comment by vsoch** [comment]
okay, if that works for you, works for me :) If at some point you want to summarize the work here, you could also do a small write up in JoSS https://joss.theoj.org/
